"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var lab_4_1 = require("./lab_4");
var Car = lab_4_1.transport.Car;
var Owner = lab_4_1.transport.Owner;
var Motorbike = lab_4_1.transport.Motorbike;
var Vehicle = lab_4_1.transport.Vehicle;
var VehicleStorage = lab_4_1.transport.VehicleStorage;
var types_doc = lab_4_1.transport.types_doc;
var dodg = new Car('Dodge', 'Challenger', '1974', '1HGCM82633A123456', 'У821НН');
var camry = new Car('Toyota', 'Camry', '2023', ' 2C4RDGBG5KR123789 ', 'К530КА');
var owner = new Owner(new Date(), 'Денис', 'Анатольевич', types_doc.Passport, '6322', '563823');
dodg.owner = owner;
var ural = new Motorbike('Ural', 'М-62', '1965', 'JH2SC5900DK100264', 'ABC123');
var IW = new Motorbike('ИЖ', 'Лидер', '1989', 'JH2SC5900DK100264', 'СИВ472');
ural.owner = owner;
var kia = new Vehicle('киа', 'Рио', '2015', 'JH2SC5900DK100264', 'У821НН');
var hunday = new Vehicle('Хендай', 'Солярис', '2014', '2C4RDGBG5KR123789', 'A001ПР');
var carStorage = new VehicleStorage();
carStorage.save(dodg);
carStorage.save(camry);
var motoStorage = new VehicleStorage();
motoStorage.save(IW);
motoStorage.save(ural);
var vehicleStorage = new VehicleStorage();
vehicleStorage.save(dodg);
vehicleStorage.save(camry);
vehicleStorage.save(ural);
vehicleStorage.save(IW);
vehicleStorage.save(kia);
vehicleStorage.save(hunday);
vehicleStorage.remove(0);
console.log(vehicleStorage.getAll());
console.log(carStorage.getAll());
console.log(motoStorage.getAll());
console.log(vehicleStorage.getAll());
